version: '3.0'

services:
  grafana:
    container_name: 'ni-systemlink-app'
    build:
      context: ./.config
    environment:
      - GF_USERS_DEFAULT_THEME=light
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/ni-systemlink-app
      - ./provisioning:/etc/grafana/provisioning
